import './index.css';
import "./array/array";
import "./array/array2";
import "./string/string";
import "./canvas/canvas";
import "./canvas/canvas.css";
import "./task";
import "./object/object";
import "./object/object3";
